apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: default
type: Opaque
data:
    # the value should be encode using base64
    KAFKA_BROKER_URI: "a2Fma2EtYnJva2VyLXNydjo5MDky"
